use soulib_db

CREATE TABLE IF NOT EXISTS CLIENTES(
    ID_CLIENTE int not null AUTO_INCREMENT PRIMARY KEY,
    NOME varchar(100) NOT NULL,
    TELEFONE VARCHAR(42) NOT NULL UNIQUE,
    EMAIL VARCHAR(120) UNIQUE
);
 DROP TABLE CLIENTES
SHOW COLUMNS FROM CLIENTES  

CREATE TABLE IF NOT EXISTS LIVROS(
    ID_LIVRO int not null AUTO_INCREMENT PRIMARY KEY,
    TITULO varchar(120) NOT NULL,
    AUTOR VARCHAR(80) NOT NULL,
    DESCRICAO VARCHAR(180) NOT NULL,
    EDITORA VARCHAR(40) NOT NULL,
    PAGINAS INT NOT NULL
);
DROP TABLE LIVROS
SHOW COLUMNS FROM LIVROS

CREATE TABLE IF NOT EXISTS EMPRESTIMOS(
    id_emprestimo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    data_realizada DATE NOT NULL,
    data_devolucao DATE NOT NULL,
    fk_cliente_id INT,
    fk_livro_id INT,
    CONSTRAINT FK_CLIENTE_ID FOREIGN KEY (fk_cliente_id) REFERENCES CLIENTES (id_cliente),
    CONSTRAINT FK_LIVRO_ID FOREIGN KEY (fk_livro_id) REFERENCES LIVROS (id_livro),
    FINALIZADO BIT DEFAULT FALSE
);


ALTER TABLE emprestimos DROP FOREIGN KEY fk_clientes_id;


ALTER TABLE emprestimos ADD CONSTRAINT fk_cliente_id FOREIGN KEY (fk_cliente_id) REFERENCES clientes(id_cliente);

ALTER TABLE emprestimos DROP FOREIGN KEY fk_livros_id;

ALTER TABLE emprestimos ADD CONSTRAINT fk_livro_id FOREIGN KEY (fk_livro_id) REFERENCES livros(id_livro);

DROP TABLE EMPRESTIMOS
SHOW COLUMNS FROM EMPRESTIMOS